name: Build and deploy Zola website to wisp.place
on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.1
        with:
          submodules: 'true'

      - name: Build Zola + upload Pages artifact
        uses: getzola/github-pages@066755243e69f508fd1a74739fbf1a65f656c790
        with:
          zola_version: v0.22.1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: wisp-deploy
    steps:
      - name: Deploy to wisp
        id: deployment
        run: |
          curl https://sites.wisp.place/nekomimi.pet/wisp-cli-binaries/wisp-cli-x86_64-linux -o wisp-cli 
          chmod +x wisp-cli 
          ./wisp-cli deploy "${{ vars.WISP_HANDLE }}" \
            --path "${{ vars.SITE_PATH }}" \
            --site "${{ vars.SITE_NAME }}" \
            --password "${{ secrets.WISP_APP_PASSWORD }}"

